services:
  app:
    build: .
    container_name: simonik_app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    container_name: simonik_db
    restart: always
    environment:
      MYSQL_DATABASE: mandiri
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - "3307:3306"